version: "{build}"

image: Visual Studio 2017

branches:
  only:
    - master
    - release

environment:
  matrix:
  - llvm: 7.1.0
  - llvm: 8.0.1
  - llvm: 9.0.0

configuration:
  - release

clone_depth: 100
skip_tags: true
skip_commits:
  files:
    - .bintray.sh
    - .ci-dockerfiles/*
    - .circleci/config.yml
    - .cirrus.yml
    - .gitattributes
    - .gitignore
    - .gitmodules
    - .travis.yml
    - .travis_commands.bash
    - .travis_install.bash
    - .travis_script.bash
    - '**/Dockerfile'
    - LICENSE
    - Makefile
    - Makefile-ponyc
    - release.bash
    - '**/*.md'
    - '**/*.txt'

clone_folder: C:\projects\ponyc

build_script:
  - ps: |
      $package_commit = git rev-parse --short --verify "HEAD^{commit}"
      $package_version = (Get-Content "VERSION")
      $package_iteration = "$package_iteration${env:appveyor_build_number}.$package_commit"
      Update-AppveyorBuild -Version "ponyc-$package_version-$package_iteration"
  - cd C:\projects\ponyc
  - python -x waf configure
  - python -x waf clean --config %configuration% --llvm %llvm%
  - python -x waf build --config %configuration% --llvm %llvm%
  - ps: |
      $ponydir = "ponyc-${package_version}-win64"
      cd C:\projects\ponyc
      md "$ponydir"
      md "${ponydir}\ponyc"
      md "${ponydir}\ponyc\bin"
      $builddir = "C:\projects\ponyc\build\${env:configuration}-llvm-${env:llvm}"
      Write-Output "Build dir is ${builddir}"
      copy $builddir\ponyc.* "${ponydir}\ponyc\bin"
      copy $builddir\ponyrt.* "${ponydir}\ponyc\bin"
      copy $builddir\*.lib "${ponydir}\ponyc\bin"
      copy -recurse packages "${ponydir}\packages"
      7z a -tzip "C:\projects\ponyc\${ponydir}.zip" "${ponydir}"

artifacts:
  - path: 'ponyc-*.zip'

deploy:
  # On branch `release`, deploy (and publish) artifacts
  # to the ponyc-win projects on Bintray.
  - provider: BinTray
    username: pony-buildbot-2
    api_key:
        secure: 4KgdDQLp2kX816XH27d5xdJBPlKGhYXN6ttdHTSt5qe1MVIF+/VResUstg0zuJ6m
    subject: pony-language
    repo: ponyc-win
    package: ponyc
    on:
        branch: release
        llvm: 7.0.1
        configuration: release
    publish: true

test_script:
  - cd C:\projects\ponyc
  - python -x waf test examples --config %configuration% --llvm %llvm%
